name: Go CI
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Install dependencies
        run: go mod tidy
      - name: Run tests
        run: go test ./...
      - name: Lint code
        run: golangci-lint run ./...
      - name: Build Docker image
        run: docker build -t myapp-go .

      - name: Push Docker image
        run: docker tag myapp-go:latest pritesh3335/myapp-go:latest && docker push pritesh3335/myapp-go:latest

