name: WordPress CI
on:
  push:
    branches:
      - main
      - 'feature/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - name: Install PHP_CodeSniffer
        run: composer global require "squizlabs/php_codesniffer=*"
      - name: Run PHPCS
        run: ~/.composer/vendor/bin/phpcs --standard=WordPress ./wordpress-app
